use_frameworks!

target 'JNHorizontalGroupAvatarCollectionView_Example' do
    pod 'JNHorizontalGroupAvatarCollectionView' , :git => 'https://github.com/JNDisrupter/JNHorizontalGroupAvatarCollectionView.git'
  
end
