use_frameworks!

target 'JNHorizontalGroupAvatarCollectionView_Example' do
  pod 'JNHorizontalGroupAvatarCollectionView', :path => '../'

  target 'JNHorizontalGroupAvatarCollectionView_Tests' do
    inherit! :search_paths

    
  end
end
